### ISSUE TITLE
Run Hymir faild

### ISSUE THREAD

**Issue by tyy0402** [dbmdz/iiif-server-hymir#12]
```
[2018-03-27 19:52:52,799 ERROR] org.apache.catalina.core.StandardService: 181 [main    ] - Failed to start connector [Connector[HTTP/1.1-9001]]
org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-9001]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.createChildManagementContext(EndpointWebMvcAutoConfiguration.java:193)
        at org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.afterSingletonsInstantiated(EndpointWebMvcAutoConfiguration.java:156)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:781)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at de.digitalcollections.iiif.hymir.Application.main(Application.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1031)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        ... 26 common frames omitted
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210)
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:990)
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:635)
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022)
        ... 27 common frames omitted
[2018-03-27 19:52:52,820  INFO] g.apache.coyote.http11.Http11NioProtocol: 179 [main    ] - Pausing ProtocolHandler ["http-nio-9001"]
[2018-03-27 19:52:52,820  INFO] org.apache.catalina.core.StandardService: 179 [main    ] - Stopping service [Tomcat]
[2018-03-27 19:52:53,137  INFO]   org.apache.catalina.util.LifecycleBase: 179 [main    ] - The stop() method was called on component [StandardServer[-1]] after stop() had already been called. The second call will be ignored.
[2018-03-27 19:52:53,138  INFO] g.apache.coyote.http11.Http11NioProtocol: 179 [main    ] - Stopping ProtocolHandler ["http-nio-9001"]
[2018-03-27 19:52:53,139  INFO] g.apache.coyote.http11.Http11NioProtocol: 179 [main    ] - Destroying ProtocolHandler ["http-nio-9001"]
[2018-03-27 19:52:53,143  INFO] org.apache.catalina.core.StandardService: 179 [main    ] - Stopping service [Tomcat]
[2018-03-27 19:52:53,167  INFO] utoConfigurationReportLoggingInitializer: 101 [main    ] -

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
[2018-03-27 19:52:53,168  INFO] ationConfigEmbeddedWebApplicationContext: 984 [main    ] - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@134b6cb: startup date [Tue Mar 27 19:52:51 CST 2018]; parent: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@73f712
[2018-03-27 19:52:53,179 ERROR] agnostics.LoggingFailureAnalysisReporter:  42 [main    ] -

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 9001 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 9001, or configure this application to listen on another port.

[2018-03-27 19:52:53,184  INFO] ationConfigEmbeddedWebApplicationContext: 984 [main    ] - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@73f712: startup date [Tue Mar 27 19:52:36 CST 2018]; root of context hierarchy
[2018-03-27 19:52:53,184  WARN] ationConfigEmbeddedWebApplicationContext:1002 [main    ] - Exception thrown from LifecycleProcessor on context close
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@73f712: startup date [Tue Mar 27 19:52:36 CST 2018]; root of context hierarchy
        at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:427)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:999)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:958)
        at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
        at de.digitalcollections.iiif.hymir.Application.main(Application.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
[2018-03-27 19:52:53,191  INFO] tuate.endpoint.jmx.EndpointMBeanExporter: 449 [main    ] - Unregistering JMX-exposed beans on shutdown
[2018-03-27 19:52:53,192  INFO] xport.annotation.AnnotationMBeanExporter: 449 [main    ] - Unregistering JMX-exposed beans on shutdown
```
I cannot figure why. The port 9001 showed `{"timestamp":"2018-03-27T11:56:40.580+0000","status":404,"error":"Not Found","message":"No message available","path":"/"}` 
I can still open port 9000 but cannot view the pictures. The problem happened suddenly.
Please help me !!!!! Tomorrow I have to show it to my tutor.

**Comment by morpheus-87** [comment]
How did you start the server? Like this: https://github.com/dbmdz/iiif-server-hymir#usage?

How does your rules yaml file (see https://github.com/dbmdz/iiif-server-hymir#image-and-presentation-manifest-resolving) look like?

On port `9001`, there lives a monitoring ui, but the correct path is `/monitoring`.

**Comment by tyy0402** [comment]
I think I find the problem. I opened VPN when I started Hymir. Perhaps the VPN used the port.

**Comment by morpheus-87** [comment]
Does it work now? Do you see your pictures?

**Comment by tyy0402** [comment]
Yes, it works! Thanks a lot!

**Comment by morpheus-87** [comment]
Great!
