### ISSUE TITLE
Error in coordinate calculations

### ISSUE THREAD

**Issue by bitzl** [dbmdz/iiif-server-hymir#212]
```http
GET localhost:9000/image/v2/bsb00041016_00002/full/142,/90/default.jpg
``` 

```
 j.l.IllegalArgumentException: Selected region (3952x2808+0+0) exceeds the image boundaries (351x494).
	at d.d.t.i.TurboJpegImageReader.read(TurboJpegImageReader.java:287)
	at d.d.i.h.i.b.ImageServiceImpl.readImage(ImageServiceImpl.java:291)
	at d.d.i.h.i.b.ImageServiceImpl.processImage(ImageServiceImpl.java:370)
	at d.d.i.h.i.f.IIIFImageApiController.getImageRepresentation(IIIFImageApiController.java:164)
	... 3 frames excluded
	at o.s.w.m.s.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at o.s.w.m.s.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	... 55 frames truncated
```

(stack_hash: aa1f0afb)

**Comment by bitzl** [comment]
Seems to be an error in combination with the rotation. Without rotation everything works as expected:

```http
GET localhost:9000/image/v2/bsb00041016_00002/full/142,/0/default.jpg
```
