### ISSUE TITLE
Requesting default.tiff instead of default.tif creates internal server error

### ISSUE THREAD

**Issue by bitzl** [dbmdz/iiif-server-hymir#215]
```http
GET localhost:9000/image/v2/bsb00130631_00005/full/full/0/default.tiff
```
should return either status code 400 (invalid request) or 301 (moved permanently) with a redirect to default.tif, but returns 500 with empty response body instead.

```
j.l.IllegalArgumentException: No enum constant de.digitalcollections.iiif.model.image.ImageApiProfile.Format.TIFF
	at java.lang.Enum.valueOf(Enum.java:240)
	at d.d.i.m.i.ImageApiProfile$Format.valueOf(ImageApiProfile.java:31)
	at d.d.i.h.i.f.IIIFImageApiController.getImageRepresentation(IIIFImageApiController.java:128)
	... 3 frames excluded
	at o.s.w.m.s.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at o.s.w.m.s.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	... 54 frames truncated
```

**Comment by bitzl** [comment]
Issue already resolved.
