### ISSUE TITLE
First tile request causes an NPE

### ISSUE THREAD

**Issue by x1rskarw** [dbmdz/iiif-server-hymir#24]
Given the setup described in [https://github.com/dbmdz/iiif-server-hymir/issues/23](https://github.com/dbmdz/iiif-server-hymir/issues/23) the first GET request for the URL
`http://localhost:10000/image/v2/viirs_9apr2015/0,0,8187,8187/512,/0/default.jpg`
causes an NPE to be thrown:
`java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Optional.<init>(Optional.java:96)
	at java.util.Optional.of(Optional.java:108)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:193)
	at java.util.stream.FindOps$FindSink$OfRef.get(FindOps.java:190)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at de.digitalcollections.iiif.hymir.image.business.ImageServiceImpl.processImage(ImageServiceImpl.java:325)`
Retrying the request right away causes the correct tile to be returned, though.

**Comment by x1rskarw** [comment]
The image format is JPEG. The rules.yaml is contained in the issue 23:
- pattern: ^(.*)$
  substitutions:
    - 'file:/C:/dev/CantaloupePix/$1.jpg'
